project:
  type: website

website:
  title: "Iasmin Goes"
  google-analytics: "G-3354DM7XJG"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: Goes-CV.pdf
        text: CV
    right:
      - text: "{{< fa envelope title = 'E-Mail' >}}"
        href: "mailto:iasmin.goes@colostate.edu"
      - text: "{{< fa brands linkedin title = 'LinkedIn' >}}"
        href: "https://www.linkedin.com/in/iasmin-goes/"
      - text: "{{< ai lattes title = 'CurrÃ­culo Lattes' >}}"
        href: "https://lattes.cnpq.br/8206286900518816"
      - text: "{{< fa brands orcid title = 'ORCID' >}}"
        href: "https://orcid.org/0000-0002-2460-3231"
      - text: "{{< ai google-scholar title = 'Google Scholar' >}}"
        href: "https://scholar.google.com/citations?user=7wKLoosAAAAJ&hl=en"
  page-footer: 
      right: "Created with [Quarto](https://quarto.org/)"
       
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

resources:
  - CNAME